### PR TITLE
Add screenshots for most themes

### PR DESCRIPTION
**Pull request by yamadapc**
These could be better taken, but I think they're an improvement and can
be improved individually by people who feel like it.

They do make the repository considerably larger in side, which is a major
downside. Feel free to move this to the wiki or something like that.

### CODE REVIEW

**Comment by yamadapc** [comment]
You can preview things here: https://github.com/yamadapc/Limechat-Themes

**Comment by jschoolcraft** [comment]
Awesome!

**Comment by yamadapc** [comment]
Are you merging this?

**Comment by jschoolcraft** [comment]
Yeah, I thought I clicked merge....

**Comment by jschoolcraft** [comment]
Ah, forgot to "commit merge".  Thanks.

**Comment by yamadapc** [comment]
No problem :)

**Pull request merged**
